### ISSUE TITLE
Encountering an error in dataset creation

### ISSUE THREAD

**Issue by lajanugen** [allenschmaltz/word_ordering#1]
On running the 4th step of dataset creation, I'm encountering the following error:
No such file or directory: '../../datasets/zgen_data/test_ref.txt'

**Comment by allenschmaltz** [comment]
To help pinpoint the issue, could you let me know what the contents (at the level of filenames) of your datasets directory looks like at the point in which you're seeing the error? As a start, just run `find .`, or equivalent, in the datasets directory and paste the filenames here, and I'll take a look.

**Comment by lajanugen** [comment]
Thank you for offering to help. I think I've got it figured. Apparently, the maltparser was not producing its outputs, which caused the subsequent stages to fail. I tried running maltparser standalone and it was complaining about log4j. I replaced the maltparser folder with my own download and the script ran to completion.

**Comment by allenschmaltz** [comment]
Thanks for pointing this out. It turns out that some of the MaltParser 1.8.1 files did not get pushed to this public repo. I went ahead and updated the repo with the applicable files in the external_tools/maltparser-1.8.1 directory (commit e00287c).
