### ISSUE TITLE
create_dataset results in empty sequence and fail to continue

### ISSUE THREAD

**Issue by colmantse** [allenschmaltz/word_ordering#2]
I am using python 2.7.18, nltk 3.4.5 (also tried 3.2.4, the oldest copy i can find on the web). 
error occur before running java so i am skipping it for now.

i am following dataset_creation.txt from dataset/preprocessing folder and everything went well until the following command: bash create_dataset.sh

> Currently processing 0 in train
Currently processing 1000 in train
Currently processing 2000 in train
Currently processing 3000 in train
Currently processing 4000 in train
Currently processing 5000 in train
Currently processing 6000 in train
Currently processing 7000 in train
Currently processing 8000 in train
Currently processing 9000 in train
Currently processing 10000 in train
Currently processing 11000 in train
Currently processing 12000 in train
Currently processing 13000 in train
Currently processing 14000 in train
Currently processing 15000 in train
Currently processing 16000 in train
Currently processing 17000 in train
Currently processing 18000 in train
Currently processing 19000 in train
Currently processing 20000 in train
Currently processing 21000 in train
Currently processing 22000 in train
Currently processing 23000 in train
Currently processing 24000 in train
Currently processing 25000 in train
Currently processing 26000 in train
Currently processing 27000 in train
Currently processing 28000 in train
Currently processing 29000 in train
Currently processing 30000 in train
Currently processing 31000 in train
Currently processing 32000 in train
Currently processing 33000 in train
Currently processing 34000 in train
Currently processing 35000 in train
Currently processing 36000 in train
Currently processing 37000 in train
Currently processing 38000 in train
Currently processing 39000 in train
Currently processing 0 in valid
Currently processing 1000 in valid
Currently processing 0 in test
Currently processing 1000 in test
Currently processing 2000 in test
Train
Total bag size: 672894, Average size of item in bag 1.411720
Base NP count: 228399, Average Base NP length: 2.212983, Token count: 949938, Sentence count: 39832
Valid
Base NP count: 9536, Average Base NP length: 2.273700, Token count: 40104, Sentence count: 1700
Test
Base NP count: 13457, Average Base NP length: 2.192465, Token count: 56674, Sentence count: 2416
split_fileid: wsj_02_dep.txt'
[]
['Hani', 'Zayadi', 'was', 'appointed', 'president', 'and', 'chief', 'executive', 'officer', 'of', 'this', 'financially', 'troubled', 'department', 'store', 'chain', ',', 'effective', 'Nov.', '15', ',', 'succeeding', 'Frank', 'Robertson', ',', 'who', 'is', 'retiring', 'early', '.']
> /media/colman/testmount/projects/trans/word_ordering/data/preprocessing/collapse_dependency_trees_based_on_bnps.py(470)filter_tree()
-> renumbered_filtered_collapsed_tree = collapse_npsyms(list(renumbered_filtered_collapsed_tree), list(wsj_filtered_tokens_one_sent_npsyms), ctr)
(Pdb) 

i looked around and it seems the problem is that the renumbered_filtered_collapsed_tree is an empty list. tracing back further, filtered_collapsed_tree is also empty. And the filtered_token at line 375 is returning None. 

If i type continue and let it goes on at the pdb, it results in assertion error, as shown below:
`(Pdb) continue
Traceback (most recent call last):
  File "ptb_to_word_ordering_dataset.py", line 42, in <module>
    sys.exit(main(sys.argv[1:]))
  File "ptb_to_word_ordering_dataset.py", line 35, in main
    save_dependency_trees(train_words, valid_words, test_words, train_bnps, valid_bnps, test_bnps, dependency_dir, filtered_dependency_dir, True)
  File "/media/colman/testmount/projects/trans/word_ordering/data/preprocessing/collapse_dependency_trees_based_on_bnps.py", line 528, in save_dependency_trees
    full_trees, filtered_trees = get_filtered_dependency_trees(dependency_dir, split_label, words, bnps)   
  File "/media/colman/testmount/projects/trans/word_ordering/data/preprocessing/collapse_dependency_trees_based_on_bnps.py", line 505, in get_filtered_dependency_trees
    filter_tree_result, lines_with_issues = filter_tree(full_tree, wsj_filtered_tokens[ctr], ctr, wsj_filtered_tokens_npsyms[ctr])
  File "/media/colman/testmount/projects/trans/word_ordering/data/preprocessing/collapse_dependency_trees_based_on_bnps.py", line 470, in filter_tree
    renumbered_filtered_collapsed_tree = collapse_npsyms(list(renumbered_filtered_collapsed_tree), list(wsj_filtered_tokens_one_sent_npsyms), ctr)        
  File "/media/colman/testmount/projects/trans/word_ordering/data/preprocessing/collapse_dependency_trees_based_on_bnps.py", line 234, in collapse_npsyms
    assert number_of_roots == 1, renumbered_filtered_collapsed_tree
AssertionError: []
`
and subsequently no file can be saved for further preprocessing.

**Comment by allenschmaltz** [comment]
Each of the 4 steps in README_DATASET_CREATION.txt are dependent on the earlier steps, so if `bash create_dependency_files.sh` failed (e.g., if the java process wasn't run in create_ptb_dependency_trees.py), then `bash create_dataset.sh` will also fail since it is dependent on the creation of the earlier files. Based on your output, it looks like some of the necessary preprocessed files did not get created in the earlier step(s).

I actually tried just now, and the following worked for me on a clean install with the newest version of the Java SDK. Could you try the following, using these exact dependencies/versions?

# Replication instructions

Create a new conda environment with python 2.7

```
conda create -n ordering_replication python=2.7

conda activate ordering_replication

pip install nltk==3.0.4
pip install numpy==1.9.2
```

Next, install Java SE Development Kit 16.0.1 https://www.oracle.com/java/technologies/javase-jdk16-downloads.html

Next, we need to download the "Resource u'corpora/ptb'" files from NLTK. (It's only 6.1kB.)
```
python
>>> import nltk
>>> nltk.download()
# a GUI will open in which you can select and download 'corpora/ptb' and then we can exit() the interpreter
```

Now try running the 4 steps in README_DATASET_CREATION.txt.

**Comment by colmantse** [comment]
> nltk.download('ptb') #also tried nltk.download('all')
[nltk_data] Downloading package ptb to /home/colman/nltk_data...
[nltk_data]   Package ptb is already up-to-date!
True

> java version "16.0.1" 2021-04-20
Java(TM) SE Runtime Environment (build 16.0.1+9-24)
Java HotSpot(TM) 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing)
javac 16.0.1

I followed your instructions. Also uninstalled java and reinstalled via the link provided. The problem persists. 

By the way, i noticed LDC99T42 has 3 tar.gz files in total. The two auxiliary files I do not know how to utilize. I just extract the main archive file and place to dataset as instructed. Wonder if things would have gone wrong there.

**Comment by allenschmaltz** [comment]
One possibility is that the directory structure is not what is expected, as you suggested. I'm not sure on the 3 tar.gz files, given my copy of LDC99T42 is just a single archive, LDC99T42.tgz. Try the following, but if this does not work, let me know the structure of your copy of LDC99T42:

```
tar -xvzf LDC99T42.tgz
cp -r treebank_3 UPTDATE_WITH_YOUR_PATH_TO_THE_REPO/datasets/
```

Now, we can check that the structure and size is what we expect.

```
cd UPTDATE_WITH_YOUR_PATH_TO_THE_REPO/datasets

datasets % ls
README.txt				treebank_3

datasets % du -sh *
4.0K	README.txt
272M	treebank_3
```

Also, let's check that `treebank_3` has the expected content, at least at a rough aggregate level:

```
datasets % du -sh treebank_3/*
 12K	treebank_3/README.ALL
4.0K	treebank_3/README1.1ST
 17M	treebank_3/docs
 56M	treebank_3/dysfl
140M	treebank_3/parsed
 59M	treebank_3/tagged
```

Note that the directory path is as follows, for example: `UPTDATE_WITH_YOUR_PATH_TO_THE_REPO/datasets/treebank_3/parsed`.

After completing the 4 steps in README_DATASET_CREATION.txt that directory should then be as follows:

```
datasets % du -sh *
4.0K	README.txt
 41M	dependency
100M	dependency_filtered_ordering_atomic
272M	treebank_3
 37M	treebank_3_original
 52M	zgen_data
 14M	zgen_data_gold
 98M	zgen_data_nonpsyms
 28M	zgen_data_npsyms_freq3_unkUNK
```

**Comment by colmantse** [comment]
> 512	README.txt
> 289M	treebank_3

> 19M	treebank_3/docs
> 57M	treebank_3/dysfl
> 141M	treebank_3/parsed
> 12M	treebank_3/raw
> 4.0K	treebank_3/README1.1ST
> 12K	treebank_3/README.ALL
> 61M	treebank_3/tagged

For the files structure after completing the all 4 stages despite encountering error and continue with pdb.

> split_fileid: wsj_02_dep.txt
> []
> ['Hani', 'Zayadi', 'was', 'appointed', 'president', 'and', 'chief', 'executive', 'officer', 'of', 'this', 'financially', 'troubled', 'department', 'store', 'chain', ',', 'effective', 'Nov.', '15', ',', 'succeeding', 'Frank', 'Robertson', ',', 'who', 'is', 'retiring', 'early', '.']
> > /media/colman/testmount/projects/trans/word_ordering/data/preprocessing/collapse_dependency_trees_based_on_bnps.py(470)filter_tree()
> -> renumbered_filtered_collapsed_tree = collapse_npsyms(list(renumbered_filtered_collapsed_tree), list(wsj_filtered_tokens_one_sent_npsyms), ctr)
> (Pdb) continue
> Traceback (most recent call last):
>   File "ptb_to_word_ordering_dataset.py", line 42, in <module>
>     sys.exit(main(sys.argv[1:]))
>   File "ptb_to_word_ordering_dataset.py", line 35, in main
>     save_dependency_trees(train_words, valid_words, test_words, train_bnps, valid_bnps, test_bnps, dependency_dir, filtered_dependency_dir, True)

> 34M	dependency
> 0	dependency_filtered_ordering_atomic
> 512	README.txt
> 290M	treebank_3
> 38M	treebank_3_original
> 0	zgen_data
> 0	zgen_data_gold
> 0	zgen_data_nonpsyms
> 0	zgen_data_npsyms_freq3_unkUNK

**Comment by colmantse** [comment]
has been able to run without problem after switching to mac, previously was running on ubuntu 16.04, thank you very much for the assistance.
